apps/organization/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from organization.views import TeachersList, OrgList, OrgHomepageView, OrgDescView, OrgCourseView, \
    TeacherListView, AddFavView, TeacherDetailView

urlpatterns = [
    url(r'^teacher/list$', TeachersList.as_view(), name="teachers_list"),
    url(r'^org_list$', OrgList.as_view(), name="org_list"),
    url(r'^org_home/(?P<org_id>\d+)$', OrgHomepageView.as_view(), name="org_detail_homepage"),
    url(r'^org_course/(?P<org_id>\d+)$', OrgCourseView.as_view(), name="org_detail_course"),
    url(r'^org_desc/(?P<org_id>\d+)$', OrgDescView.as_view(), name="org_detail_desc"),
    url(r'^teacher/list/(?P<org_id>\d+)$', TeacherListView.as_view(), name="org_teacher_list"),
    url(r'^teacher/detail/(?P<teacher_id>\d+)$', TeacherDetailView.as_view(), name="org_teacher_detail"),
    url(r'^add_fav$', AddFavView.as_view(), name="add_fav"),
]

imooc/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

import xadmin

from imooc.views import HomepageView

xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion

xversion.register_models()

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^$', HomepageView.as_view(), name="index"),
    url(r'^xadmin/', xadmin.site.urls, name='xadmin'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^course/', include('courses.urls')),  # 课程相关
    url(r'^users/', include('users.urls')),
    url(r'^org/', include('organization.urls', namespace="organization")),
    url(r'^operation/', include('operation.urls', namespace="operation")),
    # 富文本编辑器相关url
    url(r'^ueditor/', include('DjangoUeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.extend([
        url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ])

# 全局404, 500页面配置
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from DjangoUeditor.models import UEditorField
from django.db import models
from organization.models import CourseOrg, Teacher


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u"课程机构", null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u"课程名称")
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    detail = UEditorField(verbose_name='课程详情', width=600, height=300, toolbars="full", imagePath="course/ueditor/",
                          filePath="course/ueditor/", upload_settings={"imageMaxSize": 1204000}, default='')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否轮播图')
    degree = models.CharField(choices=(("cj", u"初级"), ("zj", u"中级"), ("gj", u"高级")), max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长（分钟数）")
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_num = models.IntegerField(default=0, verbose_name=u"收藏人数")
    click_num = models.IntegerField(default=0, verbose_name=u"点击数")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", null=True, blank=True, max_length=100)
    category = models.CharField(max_length=20, null=True, blank=True, verbose_name=u"课程类别")
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=10)
    teacher = models.ForeignKey(Teacher, verbose_name=u"课程老师", null=True)
    needknown = models.CharField(max_length=300, verbose_name=u"课程须知", default="")
    canlearn = models.CharField(max_length=300, verbose_name=u"课程学到什么", default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name
        app_label = "courses"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__()

    def get_zj_nums(self):
        # 获取课程章节数
        return self.lesson_set.all().count()

    get_zj_nums.short_description = '章节数'

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='http://www.projectedu.com'>跳转</a>")

    go_to.short_description = '跳转'

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        # 获取课程所有章节
        return self.lesson_set.all()


class BannerCourse(Course):
    class Meta:
        verbose_name = u"轮播课程"
        verbose_name_plural = verbose_name
        proxy = True  # 这样不会再生成一张表


# 章节
class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name
        app_label = "courses"

    def __unicode__(self):
        return "{0}({1})".format(self.course, self.name)

    def __str__(self):
        return self.__unicode__()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    url = models.URLField(max_length=200, default="", verbose_name=u"访问地址")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name
        app_label = "courses"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__()


# 课程资源
class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="course/resources/%Y/%m", verbose_name=u"资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name
        app_label = "courses"

    def __unicode__(self):
        return "{0}({1})".format(self.course, self.name)

    def __str__(self):
        return self.__unicode__()

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/org_base.html
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}公开课列表 - 慕雪在线网{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block customcss %}
    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block customejs1 %}
    {% endblock %}
</head>
<body>
<section class="headerwrap">
    <header>
        <div class=" header">
            {% block top %}
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                        <!--登录后跳转-->

                        {% if request.user.is_authenticated %}
                            <div class="personal">
                                <dl class="user fr">
                                    <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/>
                                    </dd>
                                    <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                </dl>
                                <div class="userdetail">
                                    <dl>
                                        <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                        </dt>
                                        <dd>
                                            <h2>{{ request.user.nick_name }}</h2>
                                            <p>{{ request.user.username }}</p>
                                        </dd>
                                    </dl>
                                    <div class="btn">
                                        <a class="personcenter fl" href="{% url 'usercenterinfo' %}">进入个人中心</a>
                                        <a class="fr" href="{% url 'logout' %}">退出</a>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'my_message' %}">
                                <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>
                            </a>
                        {% else %}
                            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                        {% endif %}

                    </div>
                </div>
            {% endblock %}
            {% block middle %}
                <div class="middle companyheader">
                    <div class="wp">
                        <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ org.image }}"/>
                        <div class="head fl">
                            <h1>
                                {{ org.name }}
                                <img src="{% static 'images/authentication.png' %}"/>
                                <img src="{% static 'images/gold.png' %}"/>
                            </h1>
                            <p class="fl">
                                <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                                <span class="precision company-credit" data-star-scope="5.0"></span>
                                <span class="key">5.0</span>
                            </p>
                        </div>
                        <div class="btn fr collectionbtn  notlogin" data-favid="{{ org.id }}" data-favtype="2">
                            {% if has_fav %}已收藏 {% else %}未收藏 {% endif %}
                        </div>
                    </div>
                </div>
            {% endblock %}
            {% block nav %}
            {% endblock %}
        </div>
    </header>
</section>
<section>
    {% block crumbs %}
    {% endblock %}
</section>
<section>
    <div class="wp list personal_list comp">
        {% block left %}
            <div class="left">
                <ul>
                    <li class="{% ifequal view 'homepage' %}active2{% endifequal %}"><a
                            href="{% url 'organization:org_detail_homepage' org.id %}">机构首页</a></li>
                    <li class="{% ifequal view 'course' %}active2{% endifequal %}"><a
                            href="{% url 'organization:org_detail_course' org.id %}">机构课程</a></li>
                    <li class="{% ifequal view 'desc' %}active2{% endifequal %}"><a
                            href="{% url 'organization:org_detail_desc' org.id %}">机构介绍</a></li>
                    <li class="{% ifequal view 'teachers' %}active2{% endifequal %}"><a
                            href="{% url 'organization:org_teacher_list' org.id %}">机构讲师</a></li>
                </ul>
            </div>
        {% endblock %}
        {% block right %}
        {% endblock %}
    </div>
</section>
<section>
    {% block content %}
    {% endblock %}
</section>
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
{% block customejs2 %}
    <script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
    <script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/plugins/jquery.raty.js' %}" type="text/javascript"></script>
{% endblock %}
{% block customejs3 %}
    <script>
        /**
         * Created by Administrator on 2018/5/26.
         */
        //顶部个人中心下拉框
        $('.header .personal').hover(function () {
            $('.header .userdetail').stop(true).show();
        }, function () {
            $('.header .userdetail').stop(true).hide();
        });
        //收藏分享
        //取消收藏
        function add_fav(current_elem, fav_id, fav_type) {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'organization:add_fav' %}",
                data: {'fav_id': fav_id, 'fav_type': fav_type},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'fail') {
                        if (data.msg == '用户未登录') {
                            window.location.href = "{% url 'login' %}";
                        } else {
                            alert(data.msg)
                        }

                    } else if (data.status == 'success') {
                        current_elem.text(data.msg)
                    }
                },
            });
        }

        $('.collectionbtn').on('click', function () {
            var fav_id = $(this).attr('data-favid');
            var fav_type = $(this).attr('data-favtype');
            add_fav($(this), fav_id, fav_type);
        });

        $(function () {
            var $precision = $('.precision'),
                score = $precision.attr('data-star-scope'),
                option = {
                    half: true,
                    path: '/static/images/',
                    precision: true,
                    size: 24,
                    starOff: 'g_star.png',
                    starOn: 'r_star.png',
                    starHalf: 'h_star.png',
                    hints: ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg: '暂时还未获得评价！',
                    readOnly: true,
                    score: score
                };
            $precision.raty(option);

            $('.jsFavBtn').on('click', function () {
                var type = $(this).attr('data-favtype');
                if (type == '1') {
                    favPraise($(this), 'fav', 1, '收藏');

                } else if (type == '3') {
                    favPraise($(this), 'fav', 3);

                } else if (type == '11') {
                    favPraise($(this), 'pra', 1);

                } else if (type == '4') {
                    favPraise($(this), 'fav', 4);

                }
            });
        })
    </script>
    <script>
        $(function () {
            $('.recordbtn1').click(function () {
                $('.recordbox1').show();
            });
            $('.recordbtn2').click(function () {
                $('.recordbox2').show();
            });

            $('.imgslide').unslider({
                speed: 500,               //  The speed to animate each slide (in milliseconds)
                delay: 3000,              //  The delay between slide animations (in milliseconds)
                complete: function () {
                },  //  A function that gets called after every slide animation
                keys: true,               //  Enable keyboard (left, right) arrow shortcuts
                dots: true,               //  Display dot navigation
                fluid: false              //  Support responsive design. May break non-responsive designs
            });
            var unslider = $('.imgslide').unslider();
            $('.unslider-arrow').click(function () {
                var fn = this.className.split(' ')[1];
                unslider.data('unslider')[fn]();
            });
        });
    </script>
{% endblock %}
</body>
</html>

templates/org_detail_course.html
{% extends 'org_base.html' %}
{% load staticfiles %}
{% block title %}
    机构课程列表页
{% endblock %}

{% block crumbs %}
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'organization:org_list' %}">课程机构</a>></li>
            <li>机构课程</li>
        </ul>
    </div>
{% endblock %}
{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构课程</h1>
        </div>
        <div class="brief group_list">
            {% for course in all_courses %}
                <div class="module1_5 box">
                    <a class="comp-img-box" href="course-detail">

                        <img width="214" height="195" src="{{ MEDIA_URL }}{{ course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="course-detail"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
                        <span class="fr">学习人数：{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ course.course_org.name }}</span>
                        <span class="star fr  notlogin" data-favid="{{ course.id }}" data-favtype="1">
                            {{ course.fav_num }}
                        </span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>密码修改</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <div class="error btns" id="jsResetpwdTips">
            {% for key, err in setpwd_form.errors.items %}
                {{ key }}{{ err }}
            {% endfor %}
            {{ msg }}
        </div>
        <form id="reset_password_form" action="{% url 'setpwd' %}" method="post">
            <ul>
                <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" id="jsSetpwdBtn" value="提交">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>